import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { Topbar } from "@/components/Topbar";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="min-h-screen bg-background antialiased"
      >
        <Sidebar />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          
          
          
          <div className="flex flex-1 flex-col ml-60">
            <Topbar />
            <main className="flex1 p-6">
            {children}
            </main>
          </div>
          <footer className="text-xs text-muted-foreground text-center py-3">
            v1.0.0 • LoadBalancer Go
          </footer>

        </ThemeProvider>
      </body>
    </html>
  );
}
